import Head from "next/head";
import Image from "next/image";
import axios from "axios";

import styles from "../../styles/Home.module.css";
import lottieImage from "../../components/images/lottie-6.gif";
import Showcase from "../../components/Showcase/Showcase";
import Layout from "../../sections/Layout";

// import Showcase from "../components/Showcase/Showcase";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Point Of View</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="h-64 w-64 mx-auto">
          <Image
            alt="Point of View."
            src={lottieImage}
            width={500}
            height={500}
            layout="responsive"
            objectFit="contain"
          />
        </div>
        {/* <div className="text-center my-5 text-2xl font-bold mx-auto ">
          <p>Photographs</p>
        </div> */}

        <Showcase photographs={props.photographs} />
      </Layout>
    </div>
  );
}

export const getServerSideProps = async () => {
  try {
    const res = await axios.get("http://localhost:8080/get-all");

    return {
      props: {
        photographs: res.data,
      },
    };
  } catch (error) {
    console.log(error);
  }
  return {
    props: {
      data: null,
    },
  };
};
