import Head from "next/head";
import Image from "next/image";
import Layout from "../../../sections/Layout";
import axios from "axios";
import ImageDetails from "../../../components/Showcase/ImageDetails";
import environment from "../../../environment";

const ImageDetailsPage = ({ photograph }) => {
  return (
    <div>
      <Head>
        <title>Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ImageDetails info={photograph} />
      </Layout>
    </div>
  );
};

export default ImageDetailsPage;

export const getStaticProps = async ({ params }) => {
  const host = environment.api_url;

  const { data } = await axios.get(`${host}/photograph/${params.imageId}`);
  const photograph = data;
  return {
    props: {
      photograph: photograph,
    },
  };
};

export const getStaticPaths = async () => {
  const host = environment.api_url;
  const { data } = await axios.get(`${host}/get-all`);
  const photographs = data;
  const paths = photographs.map((photo) => ({
    params: { imageId: photo._id.toString() },
  }));
  return {
    paths,
    fallback: true,
  };
};
