import Head from "next/head";
import Image from "next/image";
import AnimationDemo from "../components/Hero/AnimationDemo";
import Hero from "../components/Hero/Hero";
import LandingScreen from "../components/Hero/landingScreen";
import ScrollLinked from "../components/Hero/ScrollLinked";
import Layout from "../sections/Layout";
import styles from "../styles/Home.module.css";
import lottieImage from "../components/images/lottie-2.gif";
import Showcase from "../components/Showcase/Showcase";
// import Showcase from "../components/Showcase/Showcase";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Point Of View</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <LandingScreen />
        {/* <AnimationDemo /> */}
        {/* <ScrollLinked>🍊</ScrollLinked> */}

        <div className="h-64 w-64 mx-auto -rotate-6">
          <Image
            alt="Point of View."
            src={lottieImage}
            width={500}
            height={500}
            layout="responsive"
            objectFit="contain"
          />
        </div>
        <Showcase />
      </Layout>
    </div>
  );
}
