import Head from "next/head";
import Image from "next/image";
import AnimationDemo from "../components/Hero/AnimationDemo";
import axios from "axios";
import Hero from "../components/Hero/Hero";
import LandingScreen from "../components/Hero/landingScreen";
import ScrollLinked from "../components/Hero/ScrollLinked";
import Layout from "../sections/Layout";
import styles from "../styles/Home.module.css";
import lottieImage from "../components/images/lottie-2.gif";
import Showcase from "../components/Showcase/Showcase";
import UserInfo from "../components/user/UserInfo";
// import Showcase from "../components/Showcase/Showcase";

export default function Home(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Point Of View</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <LandingScreen />
        {/* <AnimationDemo /> */}
        {/* <ScrollLinked>🍊</ScrollLinked> */}

        <div className="h-64 w-64 mx-auto -rotate-6">
          <Image
            alt="Point of View."
            src={lottieImage}
            width={500}
            height={500}
            layout="responsive"
            objectFit="contain"
          />
        </div>
        <Showcase photographs={props.photographs} />
      </Layout>
    </div>
  );
}

export const getServerSideProps = async () => {
  try {
    const res = await axios.get("http://localhost:8080/get-all");

    return {
      props: {
        photographs: res.map((photo) => photo),
      },
    };
  } catch (error) {
    console.log(error);
  }
  return {
    props: {
      data: null,
    },
  };
};
