import Head from "next/head";
import axios from "axios";

import styles from "../styles/Home.module.css";
import Layout from "../sections/Layout";
import SignInForm from "../components/user/auth/SignInForm";

export default function SignIn(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Point Of View</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <SignInForm />
      </Layout>
    </div>
  );
}

export const getServerSideProps = async () => {
  const host = process.env.NEXT_PUBLIC_API_HOST;
  try {
    const res = await axios.get(`${host}/get-all`);

    return {
      props: {
        photographs: res.data.filter((photo) => photo.isFeatured),
      },
    };
  } catch (error) {
    console.log(error);
  }
  return {
    props: {
      data: null,
    },
  };
};
