import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import CustomModal from "../../components/CustomModal";
import Form from "../../components/Form";
import Layout from "../../sections/Layout";

export default function CreatePage() {
  return (
    <div>
      <Head>
        <title>Point Of View</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Form />
      </Layout>
    </div>
  );
}
